import { CameraApiType, CameraVirtualizationStatus, TargetProfile } from '../types.ts';

export const INITIAL_PROFILES: TargetProfile[] = [
  {
    id: 'open_camera',
    appName: 'Open Camera',
    packageName: 'net.sourceforge.opencamera',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'CameraController2 (CameraDevice) / CameraController1 (Camera)',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'LSPatch APK Patching / LSPosed Module',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: false,
    requiresPrivilegedAccess: false,
    knownLimitations: 'Supports both Camera2 API and Original Camera API modes in Settings.',
    diagnosticInfo: 'Target hooks CameraManager.openCamera, CameraDevice.createCaptureSession, and Camera.setPreviewDisplay/Texture.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'zesto_controlled_test_app',
    appName: 'Zesto Controlled Camera Test',
    packageName: 'com.example.zesto.testtarget',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'TextureView / SurfaceDirect IPC Bridge',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'Direct In-App Harness (Self-contained)',
    requiredPermissions: ['android.permission.CAMERA', 'android.permission.INTERNET'],
    requiresInstrumentation: false,
    requiresRoot: false,
    requiresPrivilegedAccess: false,
    knownLimitations: 'None (Fully instrumented reference test harness)',
    diagnosticInfo: 'Reference camera pipeline for validating OBS RTSP -> Decoder -> Surface injection without third-party sandboxing.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'discord',
    appName: 'Discord',
    packageName: 'com.discord',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'org.webrtc.Camera2Enumerator -> SurfaceTextureHelper',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'LSPatch APK Patching (Portable Mode) / LSPosed',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: false,
    requiresPrivilegedAccess: false,
    knownLimitations: 'WebRTC SurfaceTextureHelper requires surface interception via LSPatch or LSPosed.',
    diagnosticInfo: 'Target hooks org.webrtc.Camera2Session and android.hardware.camera2.CameraDevice. Physical target-app verification required.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'whatsapp',
    appName: 'WhatsApp',
    packageName: 'com.whatsapp',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'CameraDevice.createCaptureSession -> GlSurfaceView',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'LSPatch APK Patching / LSPosed Module',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: false,
    requiresPrivilegedAccess: false,
    knownLimitations: 'Custom EGL renderer; requires session Surface hooking.',
    diagnosticInfo: 'Hooks CameraDevice.createCaptureSession output targets. Physical target-app verification required.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'zoom',
    appName: 'Zoom Workplace',
    packageName: 'us.zoom.videomeetings',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'Custom C++ VideoCapturer -> SurfaceView',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'LSPatch APK Patching / LSPosed Module',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: false,
    requiresPrivilegedAccess: false,
    knownLimitations: 'Native capture hooks CameraDevice at Java layer before NDK ingestion.',
    diagnosticInfo: 'Hooks Java Camera2 layer prior to JNI video buffer ingestion. Physical target-app verification required.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'google_meet',
    appName: 'Google Meet',
    packageName: 'com.google.android.apps.meetings',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'WebRTC Camera2Session -> SurfaceTexture',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'LSPatch APK Patching / LSPosed Module',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: false,
    requiresPrivilegedAccess: false,
    knownLimitations: 'Package signature check requires signature spoofing in LSPatch.',
    diagnosticInfo: 'Hooks WebRTC Camera2Session. Requires signature verification bypass in non-root mode. Physical verification required.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'telegram',
    appName: 'Telegram',
    packageName: 'org.telegram.messenger',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'org.telegram.messenger.camera.CameraController',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'LSPatch APK Patching / LSPosed Module',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: false,
    requiresPrivilegedAccess: false,
    knownLimitations: 'Open-source client can also be directly compiled with Zesto IPC FrameProvider.',
    diagnosticInfo: 'Dual Camera1/Camera2 capture pipeline. Physical target-app verification required.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'instagram',
    appName: 'Instagram',
    packageName: 'com.instagram.android',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERAX,
    expectedPreviewPath: 'IGCameraService -> TextureView / HardwareBuffer',
    supportedBackend: 'CameraXIntegration',
    integrationMechanism: 'LSPosed System Hook (Root Required)',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: true,
    requiresPrivilegedAccess: true,
    knownLimitations: 'Heavy anti-tampering, Play Integrity & native attestation require root LSPosed hook.',
    diagnosticInfo: 'Proprietary camera stack with hardware buffer verification. Non-root LSPatch blocked by integrity checks.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  },
  {
    id: 'snapchat',
    appName: 'Snapchat',
    packageName: 'com.snapchat.android',
    minAndroidVersion: 24,
    targetAndroidVersion: 34,
    cameraApi: CameraApiType.CAMERA2,
    expectedPreviewPath: 'SCNDKRenderer -> HardwareBuffer Surface',
    supportedBackend: 'Camera2Backend',
    integrationMechanism: 'LSPosed System Hook (Root Required)',
    requiredPermissions: ['android.permission.CAMERA'],
    requiresInstrumentation: true,
    requiresRoot: true,
    requiresPrivilegedAccess: true,
    knownLimitations: 'Play Integrity & native attestation block non-root APK patching.',
    diagnosticInfo: 'NDK HardwareBuffer rendering pipeline. Requires system-level LSPosed hook. Physical verification required.',
    testStatus: CameraVirtualizationStatus.NOT_TESTED
  }
];
